### ISSUE TITLE
Do I need to get   pre-trained AA_TransUNet models to be able to train?I encountered the following problems during training

### ISSUE THREAD

**Issue by wy22vv** [YangYimin98/AA-TransUNet#2]
$ python train_precipitation.py

Traceback (most recent call last):
  File "train_precipitation.py", line 10, in <module>
    from Models.AA_TransUNet import AA_TransUnet
  File "/media/ubuntu/HDD/wangyu/AA_TransUNet/Models/AA_TransUNet.py", line 12, in <module>
    from Precipitation_Forecasting.precipitation_lightning_base import Precip_regression_base
ModuleNotFoundError: No module named 'Precipitation_Forecasting'

**Comment by YangYimin98** [comment]
你好：

你这个看起来是路径错误，训练的话不需要我的预训练模型。
________________________________
From: wy22vv ***@***.***>
Sent: Saturday, October 8, 2022 2:14:21 PM
To: YangYimin98/AA-TransUNet ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [YangYimin98/AA-TransUNet] Do I need to get pre-trained AA_TransUNet models to be able to train?I encountered the following problems during training (Issue #2)


$ python train_precipitation.py

Traceback (most recent call last):
File "train_precipitation.py", line 10, in
from Models.AA_TransUNet import AA_TransUnet
File "/media/ubuntu/HDD/wangyu/AA_TransUNet/Models/AA_TransUNet.py", line 12, in
from Precipitation_Forecasting.precipitation_lightning_base import Precip_regression_base
ModuleNotFoundError: No module named 'Precipitation_Forecasting'

―

**Comment by YangYimin98** [comment]
建议尝试colab的demo，如果不方便使用colab，可以把代码粘贴到ide里或者对着colab的代码较正自己的代码
________________________________
